# Generated by Django 5.1.4 on 2024-12-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketra_app', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
